#ifndef TESTCASE_OBSERVER_H_jmi439j89jgu45hgidcosamkmoqxoiwqdmciurenvifnbvujhrtngbgjfioerfklnjweoifjwe4iofgjk
#define TESTCASE_OBSERVER_H_jmi439j89jgu45hgidcosamkmoqxoiwqdmciurenvifnbvujhrtngbgjfioerfklnjweoifjwe4iofgjk

class testcase_observer
{
public:
	virtual ~testcase_observer() {};
};

#endif